In [1]:
import numpy as np

In [2]:
x=np.array([1,2])

In [3]:
x

array([1, 2])

In [7]:
w=np.array([[4,8] ,[6,3]])

In [8]:
w

array([[4, 8],
       [6, 3]])

In [9]:
x.dot(w)

array([16, 14])

In [10]:
a=np.array([1,4,7])

In [11]:
a

array([1, 4, 7])

In [13]:
b=np.array([
    [2,8,7],
    [1,9,3],
    [6,4,0]
    ])

In [14]:
b

array([[2, 8, 7],
       [1, 9, 3],
       [6, 4, 0]])

In [15]:
a.dot(b)

array([48, 72, 19])