In [ ]:
import numpy as np

In [ ]:
a = np.array([[1],[3]])

In [ ]:
a

array([[1],
       [3]])

In [ ]:
b = np.array([[2],[4]])

In [ ]:
b

array([[2],
       [4]])

In [ ]:
a+b

array([[3],
       [7]])

In [ ]:
c = np.array([[1,2],[3,4]])

In [ ]:
c

array([[1, 2],
       [3, 4]])

In [ ]:
d = np.array([[5,6],[7,8]])

In [ ]:
d

array([[5, 6],
       [7, 8]])

In [ ]:
c+d

array([[ 6,  8],
       [10, 12]])

バイアスまで含めた順伝播の問題

In [ ]:
x = np.array([[7],[8]])

In [ ]:
x

array([[7],
       [8]])

In [ ]:
w = np.array([[3,5],[4,2]])

In [ ]:
w

array([[3, 5],
       [4, 2]])

In [ ]:
b = np.array([[1],[1]])

In [ ]:
b

array([[1],
       [1]])

In [ ]:
w.dot(x)+b

array([[62],
       [45]])

以下は復習

In [1]:
import numpy as np

In [ ]:
a=np.array([
    [1],
    [3]
         ])

In [ ]:
a

array([[1],
       [3]])

In [ ]:
b = np.array([
    [2],
    [4]
])

In [ ]:
b

array([[2],
       [4]])

In [ ]:
a+b

array([[3],
       [7]])

In [3]:
w = np.array([[3,5],[4,2]])

In [4]:
w

array([[3, 5],
       [4, 2]])

In [5]:
x = np.array([[7],[8]])

In [6]:
x

array([[7],
       [8]])

In [7]:
c = w.dot(x)+np.array([[1],[1]])

In [ ]:
c