In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [6]:
x = np.array(
    [[7],
     [4]
     ])

In [7]:
x

array([[7],
       [4]])

In [11]:
w = np.array([
    [7,4],
    [-2,-3]
])

In [12]:
w

array([[ 7,  4],
       [-2, -3]])

In [15]:
b = np.array([
    [1],
    [25]
])

In [16]:
b

array([[ 1],
       [25]])

In [21]:
a = w.dot(x)+b

In [22]:
a

array([[66],
       [-1]])

In [30]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [31]:
sigmoid(9)

0.9998766054240137

In [32]:
y = sigmoid(a)

In [33]:
y

array([[1.        ],
       [0.26894142]])