In [2]:
import numpy as np

In [3]:
#シグモイド関数を定義
def sigmoid(a):
  return 1/(1 + np.exp(-a))

In [4]:
#二乗和誤差関数を定義
def sse(y,t):
  return 0.5 * (np.sum(y-t)**2)

In [5]:
w = np.array([[0.1]])
x = np.array([[3]])
t = np.array([[1]])

In [6]:
a = w.dot(x)
a

array([[0.3]])

In [7]:
y = sigmoid(a)
y

array([[0.57444252]])

In [8]:
#二乗和誤差を誤差関数Eとして代入
E = sse(y,t)
E

0.09054958574879755

In [9]:
#wの更新式を定義する❶
def diff(y,a,x):
  return(y-1)*(1-sigmoid(a))*sigmoid(a)*x

d = diff(y,a,x)
d

array([[-0.31209319]])

In [10]:
#wの更新式を定義する❷
w = w - diff(y,a,x)
w

array([[0.41209319]])

In [19]:
#更新されたwの値を使ってもう一度誤差を計算する
a = w.dot(x)
y = sigmoid(a)

#Eは誤差がどれだけ減ったかの確認のために見る
#wの更新式には関わらない
E = sse(y,t)

In [20]:
a

array([[3.69383216]])

In [13]:
y

array([[0.77491576]])

In [14]:
E

0.02533145832272906

In [26]:
for _ in range(100):
  w = w - diff(y,a,x)
  a = w.dot(x)
  y = sigmoid(a)
  E = sse(y,t)

In [27]:
E

7.207502196757572e-05


> ここから↓は配列の書き方についてのメモ



In [ ]:
f = np.array([[0,1]])
g = np.array([0,2])

In [ ]:
#shapeでnumpy.ndarrayの形状(サイズ)をタプルで取得できる
#wは2次元配列で、行数が1、列数が2になっている
print(f.shape)
#vは1次元配列で、要素数2のタプルになっている
#要素数1のタプルには必ず末尾にkカンマがつく
print(g.shape)

(1, 2)
(2,)


In [ ]:
#printで配列の要素を確認できる
print(f)
print(g)

[[0 1]]
[0 2]


In [ ]:
#格納した変数をそのまま入力すると、データ型と要素が表示される
f

array([[0, 1]])

In [ ]:
g

array([0, 2])

In [ ]:
f = np.array([[3]])
g = np.array([[0],[1]])

In [ ]:
#xは1行1列の2次元配列
print(f.shape)
#zは2行1列の2次元配列
print(g.shape)

(1, 1)
(2, 1)



>↑配列についてのメモ終わり

